### ISSUE TITLE
Boost's signals library has been removed - can no longer compile cotter

### ISSUE THREAD

**Issue by cjordan** [MWATelescope/cotter#2]
Hey André,

[The changelog](https://www.boost.org/users/history/version_1_69_0.html) for the newest version of boost announces the signal library removal.  I'm not sure if the signals2 library is available in older versions of boost, or how much work it is to allow CMake to handle things, but your help would be appreciated!  Let me know if there's anything I can do.

**Comment by aroffringa** [comment]
Thanks for reporting Jordan. This was probably a relic as you can see in the commit message above, as boost signals is not used within cotter. However, it used to be used in aoflagger, but someone already mailed me a ticket a week ago, so that's fixed on trunk (it now uses signals2, which has been part of boost for a while, so I don't suspect it is an issue...). So after the cotter merge, trunk cotter and trunk aoflagger should compile with newest boost. I don't recommend to use trunk aoflagger on production though (e.g. fixed a nasty memory leaking bug recently that had been on trunk for a while -- but not in releases), but I'll probably release a new aoflagger version soon.

**Comment by cjordan** [comment]
Thanks André.  Out of interest, how bad is the trunk aoflagger?  I've been cotter + calibrate-ing thousands of observations lately...

**Comment by cjordan** [comment]
Thanks André.  Out of interest, how bad is the trunk aoflagger?  I've been cotter + calibrate-ing thousands of observations lately...

**Comment by aroffringa** [comment]
@cjordan as long as aoflagger's trunk compiles and runs, it should flag fine, so if you flagged your observations with trunk they should be fine. It's more that trunk doesn't always compile or run.

**Comment by cjordan** [comment]
OK, good to know.  Thanks!
