### ISSUE TITLE
PNG library required

### ISSUE THREAD

**Issue by johnsmorgan** [MWATelescope/cotter#6]
Just installing cotter on ubuntu server 18.04. CMake complained that LIB_PNG was not set. Installing libpng-dev solved the problem as far as cmake is concerned.

**Comment by johnsmorgan** [comment]
Just leaving this here in case anyone runs into the same problem.  I found that in order to successfully compile cotter I had to install `libgtkmm-3.0-dev`. Otherwise I would get errors like this during the build:

`/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libaoflagger.so: undefined reference to Cairo::Context::rectangle(double, double, double, double)'`

**Comment by aroffringa** [comment]
Your first message describes the way the CMake complains about a missing dependency -- that's the way it is supposed to work, isn't it?

The second message is a bit more technical. If you install aoflagger and build it including the gtkmm libs, then cotter needs those same libraries. You can build aoflagger without gtkmm, and then Cotter doesn't require it. However, you probably used a standard Debian package, which have been build with gtkmm, and so Cotter requires it. It's a bit confusing, but I don't want to make gtkmm a strict requirement, because many super computers don't have that. So we'll have to live with that behaviour.
